import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI Humanoid Robotics Book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Preface',
      items: ['preface'],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Nervous System',
      items: [
        'module-1/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            {
              type: 'category',
              label: 'Chapter 1: ROS 2 and the Physical AI Nervous System',
              items: [
                'module-1/1-ros2-architecture-and-communication/index',
                {
                  type: 'category',
                  label: 'Lessons',
                  items: [
                    'module-1/1-ros2-architecture-and-communication/lessons/lesson-1.1/index',
                    'module-1/1-ros2-architecture-and-communication/lessons/lesson-1.2/index',
                    'module-1/1-ros2-architecture-and-communication/lessons/lesson-1.3/index',
                    'module-1/1-ros2-architecture-and-communication/lessons/lesson-1.4/index',
                  ],
                },
              ],
            },
            'module-1/2-nodes-topics-services-robot-communication/index',
            'module-1/3-robot-description-urdf-xacro/index',
            'module-1/4-python-ros2-integration-rclpy/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            'module-2/chapter-1/index',
            'module-2/chapter-2/index',
            'module-2/chapter-3/index',
            'module-2/chapter-4/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            'module-3/chapter-1/index',
            'module-3/chapter-2/index',
            'module-3/chapter-3/index',
            'module-3/chapter-4/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            'module-4/chapter-1/index',
            'module-4/chapter-2/index',
            'module-4/chapter-3/index',
            'module-4/chapter-4/index',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
