import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI Humanoid Robotics Book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Preface',
      items: ['preface/README'],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Nervous System',
      items: [
        'module-1/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            {
              type: 'category',
              label: 'Chapter 1: ROS 2 and the Physical AI Nervous System',
              items: [
                'module-1/ros2-architecture-and-communication/index',
                {
                  type: 'category',
                  label: 'Lessons',
                  items: [
                    'module-1/ros2-architecture-and-communication/lesson-1.1-introduction-to-ros2-architecture',
                    'module-1/ros2-architecture-and-communication/lesson-1.2-environment-setup-and-workspace-creation',
                    'module-1/ros2-architecture-and-communication/lesson-1.3-basic-publisher-subscriber-implementation',
                    'module-1/ros2-architecture-and-communication/lesson-1.4-ros2-command-line-tools',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Chapter 2: Advanced ROS2 Communication Patterns',
              items: [
                'module-1/nodes-topics-services-robot-communication/index',
                'module-1/nodes-topics-services-robot-communication/nodes-multiple-communication-patterns',
                'module-1/nodes-topics-services-robot-communication/service-based-communication',
                'module-1/nodes-topics-services-robot-communication/parameter-server-configuration',
              ],
            },
            {
              type: 'category',
              label: 'Chapter 3: Robot Description with URDF and Xacro',
              items: [
                'module-1/robot-description-urdf-xacro/index',
                {
                  type: 'category',
                  label: 'Lessons',
                  items: [
                    'module-1/robot-description-urdf-xacro/lesson-3.1-introduction-to-urdf-and-robot-description',
                    'module-1/robot-description-urdf-xacro/lesson-3.2-xacro-parameterization-and-macros',
                    'module-1/robot-description-urdf-xacro/lesson-3.3-visualization-and-validation',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Chapter 4: Python-based ROS2 Integration with rclpy',
              items: [
                'module-1/python-ros2-integration-rclpy/index',
                {
                  type: 'category',
                  label: 'Lessons',
                  items: [
                    'module-1/python-ros2-integration-rclpy/lesson-4.1-python-ros2-integration-with-rclpy',
                    'module-1/python-ros2-integration-rclpy/lesson-4.2-simulation-environment-setup',
                    'module-1/python-ros2-integration-rclpy/lesson-4.3-complete-system-integration',
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/introduction',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            {
              type: 'category',
              label: 'Chapter 1 – Gazebo Simulation',
              items: ['module-2/01-Gazebo-Simulation/index'],
            },
            {
              type: 'category',
              label: 'Chapter 2 – Physics & Sensors',
              items: ['module-2/02-Physics-&-Sensors/index'],
            },
            {
              type: 'category',
              label: 'Chapter 3 – Unity Digital Twin',
              items: ['module-2/03-Unity-Digital-Twin/index'],
            },
            {
              type: 'category',
              label: 'Chapter 4 – Multi-Simulator Integration',
              items: ['module-2/04-Multi-Simulator-Integration/index'],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            'module-3/chapter-1/index',
            'module-3/chapter-2/index',
            'module-3/chapter-3/index',
            'module-3/chapter-4/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/README',
        {
          type: 'category',
          label: 'Chapters',
          items: [
            'module-4/chapter-1/index',
            'module-4/chapter-2/index',
            'module-4/chapter-3/index',
            'module-4/chapter-4/index',
          ],
        },
      ],
    },
  ],
};

export default sidebars;
